Django/Study/project/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from mybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('mybo/', views.index),

    path('mybo/', include('mybo.urls')),
    # mybo/ 로 시작되는 페이지 요청이 있는 경우에는 모두 mybo에 있는
    # urls.py 파일의 매핑 규칙을 참조하여 처리해야함
    # 결과적으로 mybo/ 로 시작되는 요청은 모두 mybo/urls파일이 담당

    # localhost(www.naver.com):8000/mybo/
    # 127.0.0.1(100,200,200,5):8000(포트번호는 0~65535번 까지 있음)
    # 삼성전자 주소 : 가전기기사업부/...
    # 대표전화(1588-1000): 구내번호(ex.99번)

    # ex)
    # url 페이지 요청                   요청 처리 담당 파일
    # mybo/question/create/             mybo/urls.py
    # mybo/answer/search/               mybo/urls.py
    #     그 외                         config/urls.py
]
# mybo 주소와 views파일의 index함수를 매핑함
# 'mybo/' => http://127.0.0.1:8000/mybo 주소로 인식함

Django/Study/project/mysite/mybo/urls.py
from django.urls import path
from . import views   # .은 현재 디렉토리(mybo 폴더, 패키지)

app_name='mybo' # 네임스페이스 (서로 다른 앱에서 동일한 별칭이 사용가능하도록) 설정

urlpatterns=[
    path('',views.index, name='index'),
    path('<int:question_id>/',views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),

    # path('question/creat/',...),
]

#/mybo/ => 별칭 : index
#/mybo/3 => 별칭 : detail
# <int:question_id> : id(1~)

Django/Study/project/mysite/mybo/models.py
from django.db import models

# Create your models here.


class Question(models.Model):#붕어빵기계==Question(클래스)
                            #붕어빵 == 각각의 질문
    subject=models.CharField(max_length=200) #제목 속성(붕어빵 크기)
    content=models.TextField() #게시글 본문(붕어빵 내용물)
    create_date=models.DateTimeField()#게시일(붕어빵 무게)

    def __str__(self):
        return self.subject




class Answer(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    #답변은 질문과 연결되어 있어야함
    #답변과 연결된  질문이 삭제된다면 -> 답변도 삭제한다는 의미(on_delete=models.CASCADE)

    content = models.TextField()
    create_date = models.DateTimeField()

# 모델 간 연결은 models.ForeignKey() 사용

Django/Study/project/mysite/mybo/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from .models import Question
from django.utils import timezone
# Create your views here.

def index(request):
    question_list=Question.objects.order_by('-create_date')
    context={'question_list':question_list}

    return render(request, 'mybo/question_list.html', context)

# render함수는 context에 있는 질문 데이터를 템플릿(mybo/question_list.html)을
# 적용하여 html 코드로 변환해서 출력
# 템플릿 파일들을 저장하기 위한 폴더 생성


def detail(request, question_id):
    #question=Question.objects.get(id=question_id)
    question = get_object_or_404(Question,pk=question_id)
    context={'question':question}
    return render(request,'mybo/question_detail.html', context)


# /mybo/answer/create/2 ->question_id에 2가 전달됨.
# request에는 mybo/question_detail.html에서 textarea에 입력된 내용이 전달됨
# (content=request.POST.get('content')코드는 textarea에 입력된 내용을 추출
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'),
                               create_date=timezone.now())
    return redirect('mybo:detail', question_id=question.id)

Django/Study/project/mysite/templates/mybo/question_detail.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
<div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'mybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="form-group">
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>


<!--
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

<h1>{{ question.subject }}</h1>

<div>
    {{ question.content }}
</div>

<h5>{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
<div>
    <ul>
    {% for answer in question.answer_set.all %}
        <li>{{ answer.content }}</li>
    {% endfor %}
    </ul>
</div>




<form action="{% url 'mybo:answer_create' question.id %}" method="post">
{% csrf_token %}
<textarea name="content" id="content" rows="15"></textarea>
<input type="submit" value="답변등록">
</form>
-->



<!--

1. http://localhost:8000/mybo/
2. 게시글 선택 :
http:// localhost:8000/mybo/3/
-> config/urls.py
-> mybo/urls.py
-><int:question_id>/ 과 매칭되므로
-> views.detail 로 이동

-->

Django/Study/project/mysite/templates/mybo/question_list.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'mybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>





<!--템플릿 태그: html문서 내부에 동적인 코드를 삽입하기 위해 사용되는 태그-->
<!--템플릿 태그는 {#{% 와 %}#}로 둘러쌓인 문장-->
<!--**게시글 목록**-->
<!--{% if question_list %}-->
<!--    <ul>-->
<!--    {% for question in question_list %}-->
<!--        {#mybo//{{question.id}} => url 'detail' question.id #}-->
<!--        <li>-->
<!--            <a href="{% url 'mybo:detail' question.id%}">{{ question.subject }}</a>-->
<!--        </li>-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>질문이 없습니다.</p>-->
<!--{% endif %}-->

<!--&lt;!&ndash;-->
<!--/mybo/ => 별칭 : index-->
<!--/mybo/3 => 별칭 : detail-->
<!--&ndash;&gt;-->

<!--{% for item in question_list %}-->
<!--    <p>순서: {{ forloop.counter }} </p>-->
<!--    <p>{{ item }}</p>-->
<!--{% endfor %}-->